server:
  port: 9000

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/user/**, /auth/**
        - id: PRODUCT-SERVICE
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path= /private/product/**, /public/product/**, /public/category/**, /private/category/**
          filters:
          - AuthenFilter
        - id: ORDER-SERVICE
          uri: lb://ORDER-SERVICE
          predicates:
          - Path= /public/order/**, /private/order/**
          filters:
          - AuthenFilter
        - id: PAYMENT-SERVICE
          uri: lb://PAYMENT-SERVICE
          predicates:
          - Path= /public/payment/**
          filters:
          - AuthenFilter
        - id: NOTIFICATION-SERVICE
          uri: lb://NOTIFICATION-SERVICE
          predicates:
          - Path= /notification/**
            
      default-filters:
        # - name: AuthenFilter
        - name: DedupeResponseHeader
          args:
            name: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          "[/**]":
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8888/eureka/}
  instance:
    prefer-ip-address: true
