spring:
  application:
    name: discovery-server

server:
  port: 8888

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      # defaultZone: ${EUREKA_SERVER_URL}
      defaultZone: http://localhost:8888/eureka/
