server:
  port: 8083
spring:
  application:
    name: PAYMENT-SERVICE
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:microservice}?useSSL=false&serverTimezone=UTC
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:12345678}
    driver-class-name: com.mysql.cj.jdbc.Driver
  kafka:
    bootstrap-servers: ${KAFKA_HOSTS:localhost}:9092
    streams:
      bootstrap-servers: ${KAFKA_HOSTS:localhost}:9092
      properties:
        spring-json-trusted-packages: "*"
        processing-guarantee: at_least_once
      state-dir: /tmp/streams/1
      cleanup:
        on-shutdown: true
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8888/eureka/}
  instance:
    prefer-ip-address: true