spring:
  application:
    name: USER-SERVICE
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
  datasource:
    # url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:microservice}?useSSL=false&serverTimezone=UTC
    # username: ${DB_USER:root}
    # password: ${DB_PASSWORD:12345678}
    url: jdbc:mysql://localhost:3306/microservice
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8081

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8888/eureka/}
      # defaultZone: http://localhost:8888/eureka/
  instance:
    prefer-ip-address: true
